agiledev-students-spring-2023/final-project-quizverse

- front-end/package-lock.json
- front-end/package.json
- front-end/src/components/HomeScreen.js
- front-end/src/components/HomeScreen.module.css
- front-end/src/index.js
Creating a home screen that has a simple logo, typewriter effect, and two buttons that will later navigate to the respective screens.
> Add a home screen that has login and sign up buttons

- front-end/src/App.js
- front-end/src/components/DailyQuiz/DailyQuiz.js
- front-end/src/components/Header/Header.js
Initialized daily quiz page, implemented routing to daily-quiz and added link to daily-quiz in header.
> Created Daily Quiz page

- front-end/src/App.js
- front-end/src/components/Landing/Landing.js
- front-end/src/components/Landing/Login.css
- front-end/src/components/Landing/Login.js
- front-end/src/components/Landing/SignUp.css
- front-end/src/components/Landing/SignUp.js
- front-end/src/components/Landing/UserContext.js
- front-end/src/index.js
Created a simply designed login interface.
Created a simply designed create account form interface.
Linked the created account credentials to the login credentials for the running instance.
Successfully logging in brings you to main home page menu. Otherwise, try entering credentials again.
> Implemented and styled basic login and signup.

- front-end/src/components/Search/Search.js
- front-end/src/components/Search/Search.module.css
> Add a Search component

- front-end/src/components/FlashcardSet/FlashcardSet.js
> Create a flashcard set component

- front-end/src/components/Footer/Footer.css
- front-end/src/components/Header/Header.css
- front-end/src/components/Header/Header.js
- front-end/src/components/Landing/Landing.module.css
- front-end/src/components/Layout/Layout.css
* Header will no longer be covered by page elements
* Footer now always display at bottom of page
* Centered page container using flexbox
> Layout optimization

- back-end/routes/auth.js
- back-end/server.js
> update routing middleware interaction

- back-end/package.json
- back-end/routes/flashcards.js
- back-end/routes/settings.js
- back-end/server.js
- front-end/src/components/Settings/Settings.js
> User story/35/task/137/implement backend

- back-end/routes/edit-set.js
- back-end/server.js
Related to issue #149 
Placeholder get and post routes for set editting
> User story/3/task/149/edit set screen

- back-end/routes/edit-set.js
- front-end/src/App.js
- front-end/src/components/CreateSet/CreateSet.js
- front-end/src/components/EditSet/EditSet.js
Implemented front-end edit set screen interaction with back-end
Related to #18
> User story/3/task/18/edit set page

- front-end/src/components/FlashcardSets/FlashcardSet/FlashcardSet.js
- front-end/src/components/FlashcardSets/FlashcardSets.js
Removed "view set" button", now clicking on a flashcardset will route you directly to view set page
> update to view set page routing from flashcardsets page

- back-end/routes/create-set.js
- back-end/src/test/create_test.js
> implemented testing for create-set route

- back-end/routes/edit-set.js
- back-end/routes/flashcard-sets.js
- back-end/server.js
- back-end/src/test/create_test.js
- back-end/src/test/edit_test.js
- front-end/src/components/EditSet/EditSet.js
- front-end/src/components/ViewSet/ViewSet.js
> Update to flashcard-set route and its usage in edit/view, implemented unit test for edit-set route

- back-end/package.json
- back-end/routes/create-set.js
- back-end/routes/daily-quiz.js
- back-end/routes/edit-set.js
- back-end/server.js
- back-end/tests/auth_test.js
- back-end/tests/create_test.js
- back-end/tests/dailyquiz_test.js
- back-end/tests/edit_test.js
- back-end/tests/footer_test.js
- back-end/tests/settings_test.js
Changed all tests to use Supertest for making server requests instead, improvements to code coverage through this strategy.
> improve code coverage

- back-end/tests/flashcardsets_test.js
> Unit tests for flashcard sets routes

- back-end/tests/home_test.js
Mockaroo seems to have reached it's limit, but the test coverage indicates to me that I've tested the route that I planned to
> Unit tests to ensure that the home page retrieves the user data

- back-end/routes/flashcards.js
- back-end/tests/flashcards_test.js
> Add a test to confirm images POST to the back-end successfully

- back-end/routes/auth.js
- back-end/routes/settings.js
- back-end/tests/auth_test.js
> removing final ignores hopefully

- back-end/schemas/flashcard-set-schema.js
- back-end/schemas/history-schema.js
- back-end/schemas/user-schema.js
Defined a new schema for history, updated flashcardset schema to use a schema for each individual card, and added document references for user schema
Closes #216
> User story/8/task/216/define history schema

- back-end/schemas/dailyquizHistory-schema.js
- back-end/schemas/history-schema.js
- back-end/schemas/item-schema.js
- back-end/schemas/user-schema.js
> Defined daily quiz history schema

- back-end/routes/create-set.js
- back-end/schemas/flashcard-set-schema.js
```
{
createdBy: 'John',
flashcards: { _id: new ObjectId("643d33451234ca02aab9eece") },
_id: new ObjectId("643d33451234ca02aab9eecd"),
createdAt: 2023-04-17T11:53:41.180Z,
editedAt: 2023-04-17T11:53:41.180Z
}
```
> Create a new FlashcardSet when the route is reached

- back-end/routes/create-set.js
- back-end/schemas/flashcard-set-schema.js
Brought back commented code to facilitate set storage again and now store set id instead of set information
> update to create-set logic and author reference

- back-end/routes/edit-set.js
- back-end/routes/flashcard-sets.js
- back-end/schemas/history-schema.js
- front-end/src/components/CreateSet/CreateSet.js
- front-end/src/components/EditSet/EditSet.js
- front-end/src/components/FlashcardSets/FlashcardSet/FlashcardSet.js
- front-end/src/components/FlashcardSets/FlashcardSets.js
- front-end/src/components/ViewSet/ViewSet.js
Fixed edit-set UI display to display user's sets, and implemented storing of the user's updated cards when they click save.
> Edit set interactions update

- front-end/src/components/CreateSet/CreateSet.js
- front-end/src/components/ViewSet/ViewSet.js
Otherwise, these alerts seems to be empty
> Re-order promise alerts and it's id to prevent empty alerts

- front-end/src/components/FlashcardSets/FlashcardSets.js
- front-end/src/components/Layout/Header/Burger.js
- front-end/src/components/Layout/Header/Header.module.css
- front-end/src/components/ViewSet/ViewCard.js
> User story/68/task/view flashcard sets screen

- back-end/routes/daily-quiz.js
Fixed streak algorithm to reset streak to 0 after 24hrs since last quiz
> update to streak algorithm

- front-end/src/components/FlashcardSets/FlashcardSet/FlashcardSet.js
- front-end/src/components/Layout/Footer/Footer.js
- front-end/src/components/Shop/Shop.js
Related to #274 
Cleaning the console
> User story/35/task/274/use items

- back-end/routes/daily-quiz.js
Fixed streak to be +1 instead of +2 due to duplicate update calls
> User story/5/task/269/dailyquiz functionality

- back-end/routes/auth.js
- front-end/src/components/SignUp/SignUp.js
When user registers they are then directly logged into the homepage without having to login themselves. The token is passed as well. The user can later logout and login if desired.
> Register Directly Logins to Home
